Добавил файлы с данными и реализовал пару фич
Nauruz005/FitnesClub pull request #2
Opened 2023-05-24 15:03 UTC by Nauruz005

Добавил файлы с данными и реализовал пару фич

2023-06-24 19:39 UTC, NLCodeTeam requested changes

2023-06-24 19:39 UTC, NLCodeTeam commented on src/main/kotlin/data/sourse/FitnesClubDataSourseImpl.kt
>          val bufferedReader = Files.newBufferedReader(Paths.get(fileNameOne))
надо закрыть стрим

2023-06-24 19:39 UTC, NLCodeTeam commented on src/main/kotlin/data/sourse/FitnesClubDataSourseImpl.kt
> +        val (name, id, status) = client.split(",")
delimeter Должен быть вынесен

2023-06-24 19:39 UTC, NLCodeTeam commented on src/main/kotlin/domain/FitnesClubUseCaseImpl.kt
> +        val countByElement = repository.getTrainer().filter { it.name != "No" }.groupingBy { it.name }.eachCount()
убрать хотя бы в константу

2023-06-24 19:39 UTC, NLCodeTeam commented on src/main/kotlin/domain/FitnesClubUseCaseImpl.kt
> +           clientStatus = "VIP"
это должен быть как минимум enum class

2023-06-24 19:39 UTC, NLCodeTeam commented on src/main/kotlin/domain/FitnesClubUseCaseImpl.kt
> +        if(id == getClientId(id)?.id && id == getTicketId(id)?.idTicket && getTicketId(id)?.price!! >= 2000){
нельзя использовать в коде !!, только в местах вызова Java кода

2023-08-15 15:59 UTC, merged

2023-08-15 16:06 UTC, Nauruz005 commented on src/main/kotlin/domain/FitnesClubUseCaseImpl.kt
> +        val countByElement = repository.getTrainer().filter { it.name != "No" }.groupingBy { it.name }.eachCount()
Есть